Lk adminpoppa
YoDrive/Course_Work pull request #105
Opened 2024-01-04 16:35 UTC by tanyginvv

2024-01-04 22:34 UTC, DmitryIldyukov requested changes

2024-01-04 22:34 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/editCarPopUp.tsx
> +        {content}
Без {content}, сделай попап полностью отдельным компонентом. Как пример в bookingPage попапы сделаны. Иначе будут неправильно отправляться запросы

2024-01-04 22:34 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/editCarPopUp.module.css
> +    background: rgba(0, 0, 0, 0.3);
Заменить на hex

2024-01-04 22:34 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/editor.tsx
> +                    <button onClick={prewievHandler} className={styles.buttonPrewiev} style={{ background: prewiev ? "#212528" : "#d9d9d9",
Вынести в className
className={styles.buttonPrewiev + preview ? styles.Какой-то стиль : styles.Другой стиль}

2024-01-04 22:34 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/editor.tsx
> +                    <button onClick={prewievHandler} className={styles.buttonPrewiev} style={{ background: prewiev ? "#212528" : "#d9d9d9",
А еще переименовать prewiev в preview

2024-01-04 22:34 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/editor.tsx
> +                    <button onClick={addFunc} className={styles.buttonAdd} style={{ background: add ? "#212528" : "#d9d9d9",
Вынести в className

2024-01-04 22:40 UTC, DmitryIldyukov requested changes

2024-01-04 22:40 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/prewiev.tsx
> +                                {image ? <img src={URL.createObjectURL(image)} style={{width: "100%", height:"100%", objectFit:"contain"}} />:<img className={styles.spaceIcon} src={`data:image/png;ba
Вынести в className

2024-01-05 09:43 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/editCarPopUp.module.css
> +    background: rgba(0, 0, 0, 0.3);
сделал

2024-01-05 10:02 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/editor.tsx
> +                    <button onClick={prewievHandler} className={styles.buttonPrewiev} style={{ background: prewiev ? "#212528" : "#d9d9d9",
сделал

2024-01-05 10:04 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/editor.tsx
> +                    <button onClick={addFunc} className={styles.buttonAdd} style={{ background: add ? "#212528" : "#d9d9d9",
сделал

2024-01-05 10:14 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/prewiev.tsx
> +                                {image ? <img src={URL.createObjectURL(image)} style={{width: "100%", height:"100%", objectFit:"contain"}} />:<img className={styles.spaceIcon} src={`data:image/png;ba
вынес

2024-01-05 10:39 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/editCarPopUp.tsx
> +        {content}
все

2024-01-05 11:08 UTC, DmitryIldyukov approved these changes

2024-01-05 11:08 UTC, merged