сделал бургер меню и лк
YoDrive/Course_Work pull request #34
Opened 2023-10-07 14:38 UTC by tanyginvv

сделал бургер меню, переверстал лк, сверстал мои данные и историю бронирований сделал их переключение

2023-10-07 15:38 UTC, DmitryIldyukov requested changes

2023-10-07 15:38 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/office.tsx
> +                    {story && <div className={styles.info}>
Отдельный компонент

2023-10-07 15:38 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/office.tsx
> +                    {date && <div className={styles.info}>
Отдельный компонент

2023-10-07 15:38 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/office.tsx
> +    const[date, setDate] = useState(true);
Исправить на data

2023-10-07 15:38 UTC, DmitryIldyukov commented on yo_drive_client/src/components/header/header.module.css
> +    position: absolute;
Можно ли без position: absolute?

2023-10-07 15:38 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/office.module.css
> +.blockText_first{
Что то очень странное, почему у них разные margin-right?
Нужно отодвинуть флексами

2023-10-08 08:28 UTC, DmitryIldyukov requested changes

2023-10-08 08:28 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/office.tsx
> +                           <div className={styles.calendar}>
Выпадающий список (ul li)

2023-10-08 08:37 UTC, DmitryIldyukov commented
Также прыгает меню при открытии/закрытии, крестик и 3 полоски разных размеров, должно оставаться серым при выборе в меню слева (изначально должно гореть у Мои Данные)

2023-10-09 19:22 UTC, DmitryIldyukov requested changes

2023-10-09 19:22 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/story.tsx
> +                                <StoryBlock/>
Попробуй создать модель storyBlock.model.ts с полями, сделай тестовый массив и извлекай оттуда компоненты

2023-10-09 19:22 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/storyBlock.tsx
> +            <p className={styles.blockText_first}>Mercedes-Benz G63 AMG</p>
Извлекай поля из модели

2023-10-09 19:22 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/data.tsx
> +                                <h2 className={styles.name}>Фамилия</h2>
Доставать с тестовой модели

2023-10-09 19:22 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/officeAdmin.tsx
> +                    {statics && <Statics/>}
Statistics

2023-10-15 07:48 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/officeAdmin.tsx
> +                    {statics && <Statics/>}
поменял

2023-10-15 07:48 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/data.tsx
> +                                <h2 className={styles.name}>Фамилия</h2>
это только верстка

2023-10-15 07:48 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/storyBlock.tsx
> +            <p className={styles.blockText_first}>Mercedes-Benz G63 AMG</p>
верстка

2023-10-15 07:48 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/story.tsx
> +                                <StoryBlock/>
верстка

2023-10-15 07:49 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/office.tsx
> +                           <div className={styles.calendar}>
так и есть li в story block

2023-10-15 07:53 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/office.module.css
> +.blockText_first{
чо?

2023-10-15 08:31 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/office.tsx
> +                           <div className={styles.calendar}>
Это календарь (ну или что это, выпадающий список), сделай пока что кнопкой

2023-10-15 11:58 UTC, DmitryIldyukov approved these changes

2023-10-15 12:06 UTC, merged