Vykhodnyedorabotki
YoDrive/Course_Work pull request #76
Opened 2023-11-13 17:23 UTC by tanyginvv

2023-11-13 18:08 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +import { useForm} from "react-hook-form"
Пробел

2023-11-13 18:21 UTC, DmitryIldyukov requested changes

2023-11-13 18:21 UTC, DmitryIldyukov commented on yo_drive_client/src/models/Booking/FilterBookimgModel.tsx
ts, а не tsx

2023-11-13 18:21 UTC, DmitryIldyukov commented on yo_drive_client/src/models/Booking/FilterBookimgModel.tsx
> +enum GearBoxEnum{
Имеется в CarBookingModel.ts

2023-11-13 18:21 UTC, DmitryIldyukov commented on yo_drive_client/src/models/Booking/FilterBookimgModel.tsx
> +    automat="Автоматическая",
Не уверен что вообще так можно, обычно цифры, а не строки

2023-11-14 17:38 UTC, tanyginvv commented on yo_drive_client/src/models/Booking/FilterBookimgModel.tsx
поменял

2023-11-14 19:06 UTC, DmitryIldyukov approved these changes

2023-11-14 19:22 UTC, merged