Lk admin
YoDrive/Course_Work pull request #80
Opened 2023-11-19 12:18 UTC by tanyginvv

2023-11-19 13:55 UTC, DmitryIldyukov requested changes

2023-11-19 13:55 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
Через className

2023-11-19 13:55 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
Через className

2023-11-19 13:55 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
Через ClassName

2023-11-19 13:55 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
Через className

2023-11-19 13:55 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
Через ClassName

2023-11-19 13:55 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
Через className

2023-11-19 13:55 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
Через className

2023-11-19 13:55 UTC, DmitryIldyukov commented on yo_drive_client/src/models/Add/Add.model.ts
> +export enum GearBoxEnum {
Уже имеется, лучше вынести этот enum из CarBookingModel.ts в какой нибудь CarModel..ts

2023-11-19 13:55 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/storyBlock.tsx
> +                <div className={styles.popup}>
Пора забирать все из модели, а то мы замучаемся это потом везде переделывать, лучше сразу модели использовать. Передела

2023-11-19 13:55 UTC, DmitryIldyukov commented on yo_drive_client/src/components/privateOffice/office/storyBlock.tsx
> +                <div className={styles.popup}>
Так же баг, о котором я писал (почему то открываются фильтры на вкладке добавления авто)

2023-11-19 14:04 UTC, tanyginvv commented on yo_drive_client/src/models/Add/Add.model.ts
> +export enum GearBoxEnum {
сделал

2023-11-19 14:04 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/storyBlock.tsx
> +                <div className={styles.popup}>
баг убрал, СДЕЛАЙ МОДЕЛЬ

2023-11-19 14:09 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
а

2023-11-19 14:09 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
а

2023-11-19 14:10 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
а

2023-11-19 14:10 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
а

2023-11-19 14:10 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
а

2023-11-19 14:10 UTC, tanyginvv commented on yo_drive_client/src/components/privateOffice/office/add.tsx
> +                        <div style={{height: 13, width: 2}}>
а

2023-11-20 20:32 UTC, DmitryIldyukov approved these changes

2023-11-20 20:32 UTC, merged